### PR TITLE
Minor collector fixes

### PR DESCRIPTION
**Pull request by mephi42**

### CODE REVIEW

**Comment by xrmx** [comment]
Thanks a lot!  this is a very nice patchset, splitted properly with sane commit messages. You don't see much of these around :+1:

**Comment by xrmx** [comment]
BTW do you have a name i can use in the changelog?

**Comment by mephi42** [comment]
Thank you :-) I'd prefer to go by my github userid, if possible.

**Comment by xrmx** [comment]
@mephi42 ok, fine for me. Thanks!

**Pull request merged**
